# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(575, 350)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(575, 350))
        Form.setMaximumSize(QtCore.QSize(575, 350))
        self.gridLayoutForm = QtWidgets.QGridLayout(Form)
        self.gridLayoutForm.setObjectName("gridLayoutForm")
        self.gridLayout_1 = QtWidgets.QGridLayout()
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.statusLabel = QtWidgets.QLabel(Form)
        self.statusLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.statusLabel.setObjectName("statusLabel")
        self.gridLayout_1.addWidget(self.statusLabel, 10, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 15, -1, -1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.moveDirLabel = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveDirLabel.sizePolicy().hasHeightForWidth())
        self.moveDirLabel.setSizePolicy(sizePolicy)
        self.moveDirLabel.setMinimumSize(QtCore.QSize(140, 0))
        self.moveDirLabel.setObjectName("moveDirLabel")
        self.horizontalLayout_3.addWidget(self.moveDirLabel)
        self.moveDirCheckBox = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveDirCheckBox.sizePolicy().hasHeightForWidth())
        self.moveDirCheckBox.setSizePolicy(sizePolicy)
        self.moveDirCheckBox.setChecked(True)
        self.moveDirCheckBox.setObjectName("moveDirCheckBox")
        self.horizontalLayout_3.addWidget(self.moveDirCheckBox)
        self.gridLayout_1.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.moveDirText = QtWidgets.QLineEdit(Form)
        self.moveDirText.setObjectName("moveDirText")
        self.gridLayout_1.addWidget(self.moveDirText, 8, 0, 1, 1)
        self.inputDirText = QtWidgets.QLineEdit(Form)
        self.inputDirText.setObjectName("inputDirText")
        self.gridLayout_1.addWidget(self.inputDirText, 4, 0, 1, 1)
        self.inputDirLabel = QtWidgets.QLabel(Form)
        self.inputDirLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.inputDirLabel.setObjectName("inputDirLabel")
        self.gridLayout_1.addWidget(self.inputDirLabel, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_4.setSpacing(15)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.runButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setMinimumSize(QtCore.QSize(0, 30))
        self.runButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_4.addWidget(self.runButton)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setEnabled(True)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.gridLayout_1.addLayout(self.horizontalLayout_4, 9, 0, 1, 1)
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.showKnownCheckBox = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.showKnownCheckBox.sizePolicy().hasHeightForWidth())
        self.showKnownCheckBox.setSizePolicy(sizePolicy)
        self.showKnownCheckBox.setObjectName("showKnownCheckBox")
        self.horizontalLayout_1.addWidget(self.showKnownCheckBox)
        self.fastFoldCheckBox = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fastFoldCheckBox.sizePolicy().hasHeightForWidth())
        self.fastFoldCheckBox.setSizePolicy(sizePolicy)
        self.fastFoldCheckBox.setObjectName("fastFoldCheckBox")
        self.horizontalLayout_1.addWidget(self.fastFoldCheckBox)
        self.gridLayout_1.addLayout(self.horizontalLayout_1, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stbmsCheckBox = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stbmsCheckBox.sizePolicy().hasHeightForWidth())
        self.stbmsCheckBox.setSizePolicy(sizePolicy)
        self.stbmsCheckBox.setObjectName("stbmsCheckBox")
        self.horizontalLayout_2.addWidget(self.stbmsCheckBox)
        self.saveErrorsCheckBox = QtWidgets.QCheckBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveErrorsCheckBox.sizePolicy().hasHeightForWidth())
        self.saveErrorsCheckBox.setSizePolicy(sizePolicy)
        self.saveErrorsCheckBox.setObjectName("saveErrorsCheckBox")
        self.horizontalLayout_2.addWidget(self.saveErrorsCheckBox)
        self.gridLayout_1.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.outputDirText = QtWidgets.QLineEdit(Form)
        self.outputDirText.setObjectName("outputDirText")
        self.gridLayout_1.addWidget(self.outputDirText, 6, 0, 1, 1)
        self.outputDirLabel = QtWidgets.QLabel(Form)
        self.outputDirLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.outputDirLabel.setObjectName("outputDirLabel")
        self.gridLayout_1.addWidget(self.outputDirLabel, 5, 0, 1, 1)
        self.inputDirButton = QtWidgets.QToolButton(Form)
        self.inputDirButton.setObjectName("inputDirButton")
        self.gridLayout_1.addWidget(self.inputDirButton, 4, 1, 1, 1)
        self.outputDirButton = QtWidgets.QToolButton(Form)
        self.outputDirButton.setObjectName("outputDirButton")
        self.gridLayout_1.addWidget(self.outputDirButton, 6, 1, 1, 1)
        self.moveDirButton = QtWidgets.QToolButton(Form)
        self.moveDirButton.setObjectName("moveDirButton")
        self.gridLayout_1.addWidget(self.moveDirButton, 8, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_1.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayoutForm.addLayout(self.gridLayout_1, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.inputDirText, self.outputDirText)
        Form.setTabOrder(self.outputDirText, self.moveDirText)
        Form.setTabOrder(self.moveDirText, self.moveDirCheckBox)
        Form.setTabOrder(self.moveDirCheckBox, self.runButton)
        Form.setTabOrder(self.runButton, self.showKnownCheckBox)
        Form.setTabOrder(self.showKnownCheckBox, self.stbmsCheckBox)
        Form.setTabOrder(self.stbmsCheckBox, self.fastFoldCheckBox)
        Form.setTabOrder(self.fastFoldCheckBox, self.saveErrorsCheckBox)
        Form.setTabOrder(self.saveErrorsCheckBox, self.inputDirButton)
        Form.setTabOrder(self.inputDirButton, self.outputDirButton)
        Form.setTabOrder(self.outputDirButton, self.moveDirButton)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "HHConverter"))
        self.statusLabel.setText(_translate("Form", "Ready"))
        self.moveDirLabel.setText(_translate("Form", "Move Processed Directory"))
        self.moveDirCheckBox.setText(_translate("Form", "Enable"))
        self.inputDirLabel.setText(_translate("Form", "Input Directory"))
        self.runButton.setText(_translate("Form", "Run"))
        self.showKnownCheckBox.setText(_translate("Form", "Show known hole cards"))
        self.fastFoldCheckBox.setText(_translate("Form", "Convert Zone to fast fold"))
        self.stbmsCheckBox.setText(_translate("Form", "Separate HU, 6-max, and FR"))
        self.saveErrorsCheckBox.setText(_translate("Form", "Save errors to file"))
        self.outputDirLabel.setText(_translate("Form", "Output Directory"))
        self.inputDirButton.setText(_translate("Form", "..."))
        self.outputDirButton.setText(_translate("Form", "..."))
        self.moveDirButton.setText(_translate("Form", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

